Colegio/Models/Profesor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Colegio.Models
{
    public class Profesor
    {
        public int Id { get; set; }

        [Display(Name ="Nombres")]
        [Required(ErrorMessage ="Debe ingresar los nombres")]
        public string Nombre { get; set; } = string.Empty;

        [Display(Name = "Apellidos")]
        [Required(ErrorMessage = "Debe ingresar los apellidos")]
        public string Apellido { get; set; } = string.Empty;

        [Display(Name = "Género")]
        [Required(ErrorMessage = "Debe seleccionar un género")]
        public int IdGenero { get; set; }

        [ForeignKey ("IdGenero")]
        public Genero? Genero { get; set; }

       
    }
}

Colegio/Controllers/ProfesorController.cs
using Colegio.Data;
using Colegio.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Colegio.Controllers
{
    public class ProfesorController : Controller
    {
        private readonly MyDBContext _myDBContext;

        public ProfesorController(MyDBContext myDBContext)
        {
            _myDBContext = myDBContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _myDBContext.Tab_Profesor.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            ViewBag.Genero = new SelectList(await _myDBContext.Tab_Genero.ToListAsync(), "Id", "DescGenero");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Profesor profesor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _myDBContext.Tab_Profesor.Add(profesor);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Genero = new SelectList(await _myDBContext.Tab_Genero.ToListAsync(), "Id", "DescGenero");
                return View();
            }
            catch (Exception e)
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detalle(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var profesor = await _myDBContext.Tab_Profesor
                    .Include(u => u.Genero)
                    .FirstOrDefaultAsync(u => u.Id == id);
                if (profesor == null)
                {
                    return NotFound();
                }
                return View(profesor);
            }

            catch (Exception e)
            {
                return NotFound();
            }
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                Profesor profesor = await _myDBContext.Tab_Profesor.FindAsync(id);
                if (profesor == null)
                {
                    return NotFound();
                }
                ViewBag.Genero = new SelectList(await _myDBContext.Tab_Genero.ToListAsync(), "Id", "DescGenero", profesor.IdGenero);
                return View(profesor);
            }
            catch (Exception e)
            {
                return NotFound();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Editar(Profesor profesor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _myDBContext.Update(profesor);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Genero = new SelectList(await _myDBContext.Tab_Genero.ToListAsync(), "Id", "DescGenero", profesor.IdGenero);
            }
            catch (Exception e)
            {
                return NotFound();
            }
            return View();
        }

        [HttpGet]
        public async Task <IActionResult> Eliminar(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var profesor = await _myDBContext.Tab_Profesor
                    .Include(u => u.Genero)
                    .FirstOrDefaultAsync(u => u.Id == id);

            if (profesor == null)
            {
                return NotFound();            
            }
            return View(profesor);
        }

        [HttpPost, ActionName("Eliminar")]
        public async Task<IActionResult> Eliminar(Profesor profesor)
        {
            try { 
            if(_myDBContext != null && _myDBContext.Tab_Profesor != null)
                {
                    _myDBContext.Tab_Profesor.Remove(profesor);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch(Exception e)
            {
                return NotFound();
            }
            return View();
        }
        [ResponseCache (Duration = 0,Location = ResponseCacheLocation.None,NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Colegio/Views/Profesor/Crear.cshtml
@model Colegio.Models.Profesor
@{
    ViewData["Title"] = "Nuevo Profesor";
}
<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Crear Nuevo Profesor</strong></h2>
            </div>
            <div class="card-body">
                <form asp-action="Crear" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Nombre" placeholder="Nombres">
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                        <label asp-for="Nombre">Nombres</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Apellido" placeholder="Apellidos">
                        <span asp-validation-for="Apellido" class="text-danger"></span>
                        <label asp-for="Apellido">Apellidos</label>
                    </div>
                                        
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="IdGenero" asp-items="ViewBag.Genero">
                            <option value="">Seleccione un género</option>
                        </select>
                        <span asp-validation-for="IdGenero" class="text-danger"></span>
                        <label asp-for="IdGenero">Género</label>
                    </div>

                    <div class="form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="Profesor" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>
                        <button class="btn btn btn-outline-primary btn-lg w-25" type="submit">
                            <i class="fa-regular fa-floppy-disk"></i> Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Colegio/Views/Profesor/Detalle.cshtml
@model Colegio.Models.Profesor
@{
    ViewData["Title"] = "Detalle Profesor";
}
<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Detalle Profesor</strong></h2>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Nombres: </strong>@Html.DisplayFor(m => m.Nombre)</li>
                    <li class="list-group-item"><strong>Apellidos: </strong>@Html.DisplayFor(m => m.Apellido)</li>
                    <li class="list-group-item"><strong>Género: </strong>@Model.Genero?.DescGenero</li>
                    <li class="list-group-item form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="Profesor" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

Colegio/Views/Profesor/Editar.cshtml
@model Colegio.Models.Profesor
@{
    ViewData["Title"] = "Editar Profesor";
}
<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Editar Profesor</strong></h2>
            </div>
            <div class="card-body">
                <form method="post" asp-action="Editar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-floating mb-3" hidden>
                        <input class="form-control" asp-for="Id" readonly />
                    </div>

                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Nombre" placeholder="Nombres">
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                        <label asp-for="Nombre">Nombres</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Apellido" placeholder="Apellidos">
                        <span asp-validation-for="Apellido" class="text-danger"></span>
                        <label asp-for="Apellido">Apellidos</label>
                    </div>

                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="IdGenero" asp-items="ViewBag.Genero">
                            <option value="">Seleccione un género</option>
                        </select>
                        <span asp-validation-for="IdGenero" class="text-danger"></span>
                        <label asp-for="IdGenero">Género</label>
                    </div>

                    <div class="form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="Profesor" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>
                        <button class="btn btn-outline-warning btn-lg w-25" type="submit">
                            <i class="fa-regular fa-floppy-disk"></i> Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Colegio/Views/Profesor/Eliminar.cshtml
@model Colegio.Models.Profesor
@{
    ViewData["Title"] = "Eliminar Profesor";
}


<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Eliminar Profesor</strong></h2>
            </div>
            <div class="card-body">
                <form method="post" asp-action="Eliminar">
                    <input hidden asp-for="Id" />
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Nombres: </strong>@Html.DisplayFor(m => m.Nombre)</li>
                        <li class="list-group-item"><strong>Apellidos: </strong>@Html.DisplayFor(m => m.Apellido)</li>
                        <li class="list-group-item"><strong>Género: </strong>@Model.Genero?.DescGenero</li>
                        <li class="list-group-item form-group mt-2 d-flex justify-content-center">
                            <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="Profesor" asp-action="Index">
                                <i class="fa-solid fa-arrow-left"></i> Regresar
                            </a>
                            <button class="btn btn-outline-danger btn-lg w-25" type="button" data-bs-toggle="modal" data-bs-target="#EliminarModal">
                                <i class="fa-solid fa-trash"></i> Eliminar
                            </button>

                        </li>
                    </ul>
                    <div class="modal fade" id="EliminarModal" tabindex="-1" aria-labelledby="eliminarModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Eliminar Profesor</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>¿Esta seguro que desea eliminar al profesor?</p>
                                    <p>@Html.DisplayFor(m => m.Nombre) @Html.DisplayFor(m => m.Apellido)</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-dark btn-lg w-25 mx-2" data-bs-dismiss="modal">Cancelar</button>
                                    <button class="btn btn-outline-danger btn-lg w-25" type="submit"> Eliminar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Colegio/Views/Profesor/Index.cshtml
@model IEnumerable<Colegio.Models.Profesor>
@{
    ViewData["Title"] = "Lista de Profesores";
    int contador = 1;
}

<h2 class="text-center">Lista de Profesores</h2>

<div class="row">
    <div class="offset-9 col-3 mb-3">
        <a class="btn btn-outline-dark d-block mx-auto btn-lg" asp-controller="Profesor" asp-action="Crear">
            <i class="fa-solid fa-square-plus"></i> Nuevo Profesor
        </a>
    </div>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Lista de Profesores</strong></h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if (Model.Count() > 0)
                    {
                        <table class="table table-hover" id="tabla" width="100%" cellspacing="0">
                            <thead>
                                <tr class="bg-black">
                                    <th scope="col" class="text-white">#</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.Id)</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.Nombre)</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.Apellido)</th>
                                    <th scope="col" class="text-white">Opciones</th>
                                </tr>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@contador</td>
                                        <td>@Html.DisplayFor(m => item.Id)</td>
                                        <td>@Html.DisplayFor(m => item.Nombre)</td>
                                        <td>@Html.DisplayFor(m => item.Apellido)</td>
                                        <td>
                                            <a class="btn btn-outline-primary mx-2" asp-action="Detalle" asp-route-id="@item.Id">
                                                <i class="fa-solid fa-circle-info"></i> Detalle
                                            </a>
                                            <a class="btn btn-outline-warning mx-2" asp-action="Editar" asp-route-id="@item.Id">
                                                <i class="fa-solid fa-pen-to-square"></i> Editar
                                            </a>
                                            <a class="btn btn-outline-danger mx-2" asp-action="Eliminar" asp-route-id="@item.Id">
                                                <i class="fa-solid fa-trash"></i> Eliminar
                                            </a>
                                        </td>
                                    </tr>
                                    contador++;
                                }
                            </thead>
                        </table>
                    }
                    else
                    {
                        <p class="text-center"><strong>No hay registros</strong></p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>