Colegio/Controllers/AlumnoController.cs
using Colegio.Data;
using Colegio.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Colegio.Controllers
{
    public class AlumnoController : Controller
    {
        private readonly MyDBContext _myDBContext;

        public AlumnoController(MyDBContext myDBContext)
        {
            _myDBContext = myDBContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _myDBContext.Tab_Alumno.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            ViewBag.Genero = new SelectList(await _myDBContext.Tab_Genero.ToListAsync(), "Id", "DescGenero");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Alumno alumno)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _myDBContext.Tab_Alumno.Add(alumno);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Genero = new SelectList(await _myDBContext.Tab_Genero.ToListAsync(), "Id", "DescGenero");
                return View();
            }
            catch (Exception e)
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detalle(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var alumno = await _myDBContext.Tab_Alumno
                    .Include(u => u.Genero)
                    .FirstOrDefaultAsync(u => u.Id == id);
                if (alumno == null)
                {
                    return NotFound();
                }
                return View(alumno);
            }

            catch (Exception e)
            {
                return NotFound();
            }
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                Alumno alumno = await _myDBContext.Tab_Alumno.FindAsync(id);
                if (alumno == null)
                {
                    return NotFound();
                }
                ViewBag.Genero = new SelectList(await _myDBContext.Tab_Genero.ToListAsync(), "Id", "DescGenero", alumno.IdGenero);
                return View(alumno);
            }
            catch (Exception e)
            {
                return NotFound();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Editar(Alumno alumno)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _myDBContext.Update(alumno);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Genero = new SelectList(await _myDBContext.Tab_Genero.ToListAsync(), "Id", "DescGenero", alumno.IdGenero);
            }
            catch (Exception e)
            {
                return NotFound();
            }
            return View();
        }

        [HttpGet]
        public async Task <IActionResult> Eliminar(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var alumno = await _myDBContext.Tab_Alumno
                    .Include(u => u.Genero)
                    .FirstOrDefaultAsync(u => u.Id == id);

            if (alumno == null)
            {
                return NotFound();            
            }
            return View(alumno);
        }

        [HttpPost, ActionName("Eliminar")]
        public async Task<IActionResult> Eliminar(Alumno alumno)
        {
            try { 
            if(_myDBContext != null && _myDBContext.Tab_Alumno != null)
                {
                    _myDBContext.Tab_Alumno.Remove(alumno);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch(Exception e)
            {
                return NotFound();
            }
            return View();
        }
        [ResponseCache (Duration = 0,Location = ResponseCacheLocation.None,NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Colegio/Controllers/GeneroController.cs
using Colegio.Data;
using Colegio.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Colegio.Controllers
{
    public class GeneroController : Controller
    {
        private readonly MyDBContext _myDBContext;

        public GeneroController(MyDBContext myDBContext)
        {
            _myDBContext = myDBContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _myDBContext.Tab_Genero.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Genero genero)
        {
            try
            {
                if (await _myDBContext.Tab_Genero.AnyAsync(e => e.DescGenero == genero.DescGenero))
                {
                    ModelState.AddModelError("Género", "El género ya existe.");
                }
                if (ModelState.IsValid)
                {
                    _myDBContext.Tab_Genero.Add(genero);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch (Exception e)
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detalle(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                Genero genero = await _myDBContext.Tab_Genero.FindAsync(id);
                if (genero == null)
                {
                    return NotFound();
                }
                return View(genero);
            }

            catch (Exception e)
            {
                return NotFound();
            }
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                Genero genero = await _myDBContext.Tab_Genero.FindAsync(id);
                if (genero == null)
                {
                    return NotFound();
                }
                return View(genero);
            }
            catch (Exception e)
            {
                return NotFound();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Editar(Genero genero)
        {
            try
            {
                if (await _myDBContext.Tab_Genero.AnyAsync(e => e.DescGenero == genero.DescGenero))
                {
                    ModelState.AddModelError("Género", "El género ya existe.");
                }
                if (ModelState.IsValid)
                {
                    _myDBContext.Update(genero);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception e)
            {
                return NotFound();
            }
            return View();
        }

        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Genero genero = _myDBContext.Tab_Genero.Find(id);
            if (genero == null)
            {
                return NotFound();            
            }
            return View(genero);
        }

        [HttpPost, ActionName("Eliminar")]
        public async Task<IActionResult> Eliminar(Genero genero)
        {
            try { 
            if(_myDBContext != null && _myDBContext.Tab_Genero != null)
                {
                    _myDBContext.Tab_Genero.Remove(genero);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch(Exception e)
            {
                return NotFound();
            }
            return View();
        }
        [ResponseCache (Duration = 0,Location = ResponseCacheLocation.None,NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Colegio/Controllers/GradoController.cs
using Colegio.Data;
using Colegio.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Colegio.Controllers
{
    public class GradoController : Controller
    {
        private readonly MyDBContext _myDBContext;

        public GradoController(MyDBContext myDBContext)
        {
            _myDBContext = myDBContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {


            var grados = await _myDBContext.Tab_Grado.ToListAsync();

            return View(grados);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            var profesores = await _myDBContext.Tab_Profesor
                .Select(p => new
                {
                    p.Id,
                    NombreCompleto = p.Nombre + " " + p.Apellido
                })
                .ToListAsync();

            ViewBag.Profesor = new SelectList(profesores, "Id", "NombreCompleto");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Grado grado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _myDBContext.Tab_Grado.Add(grado);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                var profesores = await _myDBContext.Tab_Profesor
                .Select(p => new
                {
                    p.Id,
                    NombreCompleto = p.Nombre + " " + p.Apellido
                })
                .ToListAsync();

                ViewBag.Profesor = new SelectList(profesores, "Id", "NombreCompleto");
                return View();
            }
            catch (Exception e)
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detalle(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var grado = await _myDBContext.Tab_Grado
                    .Include(u => u.Profesor)
                    .FirstOrDefaultAsync(u => u.Id == id);
                if (grado == null)
                {
                    return NotFound();
                }
                return View(grado);
            }

            catch (Exception e)
            {
                return NotFound();
            }
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var profesores = await _myDBContext.Tab_Profesor
               .Select(p => new
               {
                   p.Id,
                   NombreCompleto = p.Nombre + " " + p.Apellido
               })
               .ToListAsync();


                Grado grado = await _myDBContext.Tab_Grado.FindAsync(id);
                if (grado == null)
                {
                    return NotFound();
                }

                ViewBag.Profesor = new SelectList(profesores, "Id", "NombreCompleto", grado.IdProfesor);
                return View(grado);
            }
            catch (Exception e)
            {
                return NotFound();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Editar(Grado grado)
        {
            try
            {
                var profesores = await _myDBContext.Tab_Profesor
            .Select(p => new
            {
                p.Id,
                NombreCompleto = p.Nombre + " " + p.Apellido
            })
            .ToListAsync();


                if (ModelState.IsValid)
                {
                    _myDBContext.Update(grado);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Profesor = new SelectList(profesores, "Id", "NombreCompleto", grado.IdProfesor);
            }
            catch (Exception e)
            {
                return NotFound();
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var grado = await _myDBContext.Tab_Grado
                    .Include(u => u.Profesor)
                    .FirstOrDefaultAsync(u => u.Id == id);

            if (grado == null)
            {
                return NotFound();
            }
            return View(grado);
        }

        [HttpPost, ActionName("Eliminar")]
        public async Task<IActionResult> Eliminar(Grado grado)
        {
            try
            {
                if (_myDBContext != null && _myDBContext.Tab_Grado != null)
                {
                    _myDBContext.Tab_Grado.Remove(grado);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception e)
            {
                return NotFound();
            }
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Colegio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Colegio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Colegio.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Colegio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Administrar</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Grado" asp-action="Index">Grados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profesor" asp-action="Index">Profesores</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Seccion" asp-action="Index">Secciones</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Alumnos</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Alumno" asp-action="Index">Alumnos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AlumnoGrado" asp-action="Index">Asignar Grado</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Generales</a>
                            <ul class="dropdown-menu">
                               
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Genero" asp-action="Index">Genero</a>
                                </li>
                            </ul>
                        </li>
                       

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Colegio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>