Colegio/Models/AlumnoGrado.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Colegio.Models
{
    public class AlumnoGrado
    {
        public int Id { get; set; }

        [Display(Name = "Alumno")]
        [Required(ErrorMessage = "Debe seleccionar un Alumno")]
        public int IdAlumno { get; set; }

        [ForeignKey("IdAlumno")]
        public Alumno? Alumno { get; set; }


        [Display(Name = "Grado")]
        [Required(ErrorMessage = "Debe seleccionar un Grado")]
        public int IdGrado { get; set; }

        [ForeignKey ("IdGrado")]
        public Grado? Grado { get; set; }
        
        [Display(Name = "Sección")]
        [Required(ErrorMessage = "Debe seleccionar una sección")]
        public int IdSeccion { get; set; }

        [ForeignKey ("IdSeccion")]
        public Seccion? Seccion { get; set; } 
        
                
    }
}

Colegio/Controllers/AlumnoGradoController.cs
using Colegio.Data;
using Colegio.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Colegio.Controllers
{
    public class AlumnoGradoController : Controller
    {
        private readonly MyDBContext _myDBContext;

        public AlumnoGradoController(MyDBContext myDBContext)
        {
            _myDBContext = myDBContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var alumnoGrados = await _myDBContext.Tab_AlumnoGrado
                .Include(ag => ag.Alumno)
                .Include(ag => ag.Grado)
                .Include(ag => ag.Seccion)
                .ToListAsync();
            return View(alumnoGrados);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            var alumnos = await _myDBContext.Tab_Alumno
                .Select(a => new
                {
                    a.Id,
                    NombreCompleto = a.Nombre + " " + a.Apellido
                })
                .ToListAsync();

            ViewBag.Alumno = new SelectList(alumnos, "Id", "NombreCompleto");
            ViewBag.Grado = new SelectList(await _myDBContext.Tab_Grado.ToListAsync(), "Id", "Nombre");
            ViewBag.Seccion = new SelectList(await _myDBContext.Tab_Seccion.ToListAsync(), "Id", "DescSeccion");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(AlumnoGrado alumnoGrado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _myDBContext.Tab_AlumnoGrado.Add(alumnoGrado);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                var alumno = await _myDBContext.Tab_Alumno
                 .Select(a => new
                 {
                     a.Id,
                     NombreCompleto = a.Nombre + " " + a.Apellido
                 })
                 .ToListAsync();

                ViewBag.Alumno = new SelectList(alumno, "Id", "NombreCompleto");
                ViewBag.Grado = new SelectList(await _myDBContext.Tab_Profesor.ToListAsync(), "Id", "Nombre");
                ViewBag.Seccion = new SelectList(await _myDBContext.Tab_Profesor.ToListAsync(), "Id", "DescSeccion");
                return View();
            }
            catch (Exception e)
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detalle(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                AlumnoGrado alumnoGrado = await _myDBContext.Tab_AlumnoGrado.FindAsync(id);
                Alumno alumno = await _myDBContext.Tab_Alumno.FindAsync(alumnoGrado.IdAlumno);
                alumnoGrado.Alumno.Nombre = alumno.Nombre;
                alumnoGrado.Alumno.Apellido = alumno.Apellido;

                Grado grado = await _myDBContext.Tab_Grado.FindAsync(alumnoGrado.IdGrado);
                alumnoGrado.Grado.Nombre = grado.Nombre;

                Seccion seccion = await _myDBContext.Tab_Seccion.FindAsync(alumnoGrado.IdSeccion);
                alumnoGrado.Seccion.DescSeccion = seccion.DescSeccion;

                if (alumnoGrado == null)
                {
                    return NotFound();
                }

                return View(alumnoGrado);
            }

            catch (Exception e)
            {
                return NotFound();
            }
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                AlumnoGrado alumnoGrado = await _myDBContext.Tab_AlumnoGrado.FindAsync(id);
                if (alumnoGrado == null)
                {
                    return NotFound();
                }
                var alumnos = await _myDBContext.Tab_Alumno
                .Select(a => new
                {
                    a.Id,
                    NombreCompleto = a.Nombre + " " + a.Apellido
                })
                .ToListAsync();

                ViewBag.Alumno = new SelectList(alumnos, "Id", "NombreCompleto", alumnoGrado.IdAlumno);
                ViewBag.Grado = new SelectList(await _myDBContext.Tab_Grado.ToListAsync(), "Id", "Nombre", alumnoGrado.IdGrado);
                ViewBag.Seccion = new SelectList(await _myDBContext.Tab_Seccion.ToListAsync(), "Id", "DescSeccion", alumnoGrado.IdSeccion);
                return View(alumnoGrado);
            }
            catch (Exception e)
            {
                return NotFound();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Editar(AlumnoGrado alumnoGrado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _myDBContext.Update(alumnoGrado);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                var alumnos = await _myDBContext.Tab_Alumno
                .Select(a => new
                {
                    a.Id,
                    NombreCompleto = a.Nombre + " " + a.Apellido
                })
                .ToListAsync();

                ViewBag.Alumno = new SelectList(alumnos, "Id", "NombreCompleto", alumnoGrado.IdAlumno);
                ViewBag.Grado = new SelectList(await _myDBContext.Tab_Grado.ToListAsync(), "Id", "Nombre", alumnoGrado.IdGrado);
                ViewBag.Seccion = new SelectList(await _myDBContext.Tab_Seccion.ToListAsync(), "Id", "DescSeccion", alumnoGrado.IdSeccion);
            }
            catch (Exception e)
            {
                return NotFound();
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            if (id == null)
            {
                return NotFound();
            }


            AlumnoGrado alumnoGrado = await _myDBContext.Tab_AlumnoGrado.FindAsync(id);
            Alumno alumno = await _myDBContext.Tab_Alumno.FindAsync(alumnoGrado.IdAlumno);
            alumnoGrado.Alumno.Nombre = alumno.Nombre;
            alumnoGrado.Alumno.Apellido = alumno.Apellido;

            Grado grado = await _myDBContext.Tab_Grado.FindAsync(alumnoGrado.IdGrado);
            alumnoGrado.Grado.Nombre = grado.Nombre;

            Seccion seccion = await _myDBContext.Tab_Seccion.FindAsync(alumnoGrado.IdSeccion);
            alumnoGrado.Seccion.DescSeccion = seccion.DescSeccion;
            if (alumnoGrado == null)
            {
                return NotFound();
            }
            return View(alumnoGrado);
        }

        [HttpPost, ActionName("Eliminar")]
        public async Task<IActionResult> Eliminar(AlumnoGrado alumnoGrado)
        {
            try
            {
                if (_myDBContext != null && _myDBContext.Tab_AlumnoGrado != null)
                {
                    _myDBContext.Tab_AlumnoGrado.Remove(alumnoGrado);
                    await _myDBContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception e)
            {
                return NotFound();
            }
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Colegio/Views/AlumnoGrado/Crear.cshtml
@model Colegio.Models.AlumnoGrado
@{
    ViewData["Title"] = "Nuevo Alumno Grado";
}
<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Crear Nuevo Alumno Grado</strong></h2>
            </div>
            <div class="card-body">
                <form asp-action="Crear" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="IdAlumno" asp-items="ViewBag.Alumno">
                            <option value="">Seleccione un Alumno</option>
                        </select>
                        <span asp-validation-for="IdAlumno" class="text-danger"></span>
                        <label asp-for="IdAlumno">Alumno</label>
                    </div>

                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="IdGrado" asp-items="ViewBag.Grado">
                            <option value="">Seleccione un grado</option>
                        </select>
                        <span asp-validation-for="IdGrado" class="text-danger"></span>
                        <label asp-for="IdGrado">Grado</label>
                    </div>

                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="IdSeccion" asp-items="ViewBag.Seccion">
                            <option value="">Seleccione una sección</option>
                        </select>
                        <span asp-validation-for="IdSeccion" class="text-danger"></span>
                        <label asp-for="IdSeccion">Sección</label>
                    </div>

                    <div class="form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="AlumnoGrado" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>
                        <button class="btn btn-outline-primary btn-lg w-25" type="submit">
                            <i class="fa-regular fa-floppy-disk"></i> Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Colegio/Views/AlumnoGrado/Detalle.cshtml
@model Colegio.Models.AlumnoGrado
@{
    ViewData["Title"] = "Detalle Alumno-Grado";
}
<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Detalle Alumno-Grado</strong></h2>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Alumno: </strong>@Model.Alumno?.Nombre @Model.Alumno?.Apellido</li>
                    <li class="list-group-item"><strong>Grado: </strong>@Model.Grado?.Nombre</li>
                    <li class="list-group-item"><strong>Sección: </strong>@Model.Seccion?.DescSeccion</li>
                    <li class="list-group-item form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="AlumnoGrado" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

Colegio/Views/AlumnoGrado/Editar.cshtml
@model Colegio.Models.AlumnoGrado
@{
    ViewData["Title"] = "Editar Alumno-Grado";
}
<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Editar Alumno-Grado</strong></h2>
            </div>
            <div class="card-body">
                <form method="post" asp-action="Editar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-floating mb-3" hidden>
                        <input class="form-control" asp-for="Id" readonly />
                    </div>

                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="IdAlumno" asp-items="ViewBag.Alumno">
                            <option value="">Seleccione un Alumno</option>
                        </select>
                        <span asp-validation-for="IdAlumno" class="text-danger"></span>
                        <label asp-for="IdAlumno">Alumno</label>
                    </div>

                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="IdGrado" asp-items="ViewBag.Grado">
                            <option value="">Seleccione un grado</option>
                        </select>
                        <span asp-validation-for="IdGrado" class="text-danger"></span>
                        <label asp-for="IdGrado">Grado</label>
                    </div>

                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="IdSeccion" asp-items="ViewBag.Seccion">
                            <option value="">Seleccione una sección</option>
                        </select>
                        <span asp-validation-for="IdSeccion" class="text-danger"></span>
                        <label asp-for="IdSeccion">Sección</label>
                    </div>

                    <div class="form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="AlumnoGrado" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>
                        <button class="btn btn-outline-warning btn-lg w-25" type="submit">
                            <i class="fa-regular fa-floppy-disk"></i> Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Colegio/Views/AlumnoGrado/Eliminar.cshtml
@model Colegio.Models.AlumnoGrado
@{
    ViewData["Title"] = "Eliminar Alumno-Grado";
}

<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Eliminar Alumno-Grado</strong></h2>
            </div>
            <div class="card-body">
                <form method="post" asp-action="Eliminar">
                    <input hidden asp-for="Id" />
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Alumno: </strong>@Model.Alumno?.Nombre @Model.Alumno?.Apellido</li>
                        <li class="list-group-item"><strong>Grado: </strong>@Model.Grado?.Nombre</li>
                        <li class="list-group-item"><strong>Sección: </strong>@Model.Seccion?.DescSeccion</li>
                        <li class="list-group-item form-group mt-2 d-flex justify-content-center">
                            <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="AlumnoGrado" asp-action="Index">
                                <i class="fa-solid fa-arrow-left"></i> Regresar
                            </a>
                            <button class="btn btn-outline-danger btn-lg w-25" type="button" data-bs-toggle="modal" data-bs-target="#EliminarModal">
                                <i class="fa-solid fa-trash"></i> Eliminar
                            </button>
                        </li>
                    </ul>
                    <div class="modal fade" id="EliminarModal" tabindex="-1" aria-labelledby="eliminarModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Eliminar Asignación</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>¿Esta seguro que desea eliminar la asignación del alumno?</p>
                                    <p>@Model.Alumno?.Nombre @Model.Alumno?.Apellido</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-dark btn-lg w-25 mx-2" data-bs-dismiss="modal">Cancelar</button>
                                    <button type="submit" class="btn btn-outline-danger btn-lg w-25"><i class="fa-solid fa-trash"></i> Eliminar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Colegio/Views/AlumnoGrado/Index.cshtml
@model IEnumerable<Colegio.Models.AlumnoGrado>
@{
    ViewData["Title"] = "Lista de Alumno - Grados";
    int contador = 1;
}

<h2 class="text-center">Lista de Alumno - Grado</h2>

<div class="row">
    <div class="offset-9 col-3 mb-3">
        <a class="btn btn-outline-dark d-block mx-auto btn-lg" asp-controller="AlumnoGrado" asp-action="Crear">
            <i class="fa-solid fa-square-plus"></i> Asignar Alumno
        </a>
    </div>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Alumnos asignados</strong></h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if (Model.Count() > 0)
                    {
                        <table class="table table-hover" id="tabla" width="100%" cellspacing="0">
                            <thead>
                                <tr class="bg-black">
                                    <th scope="col" class="text-white">#</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.Id)</th>
                                    <th scope="col" class="text-white">Nombre Alumno</th>
                                    <th scope="col" class="text-white">Grado</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.Seccion.DescSeccion)</th>

                                    <th scope="col" class="text-white">Opciones</th>
                                </tr>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@contador</td>
                                        <td>@Html.DisplayFor(m => item.Id)</td>
                                        <td>@Html.DisplayFor(m => item.Alumno.Nombre) @Html.DisplayFor(m => item.Alumno.Apellido)</td>
                                        <td>@Html.DisplayFor(m => item.Grado.Nombre)</td>
                                        <td>@Html.DisplayFor(m => item.Seccion.DescSeccion)</td>
                                        <td>
                                            <a class="btn btn-outline-primary mx-2" asp-action="Detalle" asp-route-id="@item.Id">
                                                <i class="fa-solid fa-circle-info"></i> Detalle
                                            </a>
                                            <a class="btn btn-outline-warning mx-2" asp-action="Editar" asp-route-id="@item.Id">
                                                <i class="fa-solid fa-pen-to-square"></i> Editar
                                            </a>
                                            <a class="btn btn-outline-danger mx-2" asp-action="Eliminar" asp-route-id="@item.Id">
                                                <i class="fa-solid fa-trash"></i> Eliminar
                                            </a>
                                        </td>
                                    </tr>
                                    contador++;
                                }
                            </thead>
                        </table>
                    }
                    else
                    {
                        <p class="text-center"><strong>No hay registros</strong></p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>